#ifndef __PARSER_H_
#define __PARSER_H_
using namespace std;
#include <string>
#pragma once


typedef enum {
	TOKEN_NOT_EQUAL,
	TOKEN_GR_EQUAL,
	TOKEN_GREATER,
	TOKEN_LESS,
	TOKEN_EQ_EQUAL,
	TOKEN_EQUAL,
	TOKEN_BANG,
	TOKEN_SETC,
	TOKEN_HEADER,
	TOKEN_ELSE,
	TOKEN_LEFT_PAREN,
	TOKEN_RIGHT_PAREN,
	TOKEN_LEFT_BRACE,
	TOKEN_RIGHT_BRACE,
	TOKEN_LEFT_BLOCK,
	TOKEN_RIGHT_BLOCK,
	TOKEN_COMMA,
	TOKEN_DOT,
	TOKEN_SEMICOLON,
	TOKEN_tokenstore, TOKEN_END,


	TOKEN_BOOL,TOKEN_VAR,TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER, 
	TOKEN_PIN, TOKEN_FALSE, TOKEN_TRUE, TOKEN_FUNCALL, TOKEN_OUTPUT, TOKEN_ENDL,

	TOKEN_INFINITE, TOKEN_FUN, TOKEN_IF, TOKEN_VOID, TOKEN_ECHO,

	TOKEN_BREAK, TOKEN_WHILE, TOKEN_POUND, M_QUERY, M_CONNECT, TOKEN_EOF
	
	
}TokenType;

#endif

